FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json .
COPY pnpm-lock.yaml .
COPY turbo.json .

COPY packages ./packages
COPY apps ./apps

RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Generate Prisma client
RUN npx prisma generate --schema=./packages/db/prisma/schema.prisma

# Build the project (this must be defined in your scripts)
RUN pnpm build

EXPOSE 3002

CMD ["node", "apps/backend/dist/index.js"]
